// <auto-generated />
namespace PostGreSql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class testadbcreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testadbcreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201804030858088_testa db created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
